### ISSUE TITLE
Update guide

### ISSUE THREAD

**Issue by cosmo1234** [PaystackHQ/paystack-ios#1]
The doc need a little upgrade `if let card = paymentTextField.cardParams as? PSTCKCardParams` this particular line
And can you add some example if am trying to add card from my own textField

**Comment by ibrahimlawal** [comment]
@cosmo1234  What's wrong with the line? As for adding card from your own textFields, you can do that by creating your own `PSTCKCardParams` object and populating it.

**Comment by cosmo1234** [comment]
In the documentation it is `if let card = paymentTextField.card` which will not work `if let card = paymentTextField.cardParams as? PSTCKCardParams` this works.
Ok can u give a quick example

**Comment by ibrahimlawal** [comment]
Awesome! Thanks Fixed. It always returns a struct value so no need for the optional, I think.

Here's a swift sample packing the cardParams (The implementation in the library uses a similar method as shown here: https://github.com/PaystackHQ/paystack-ios/blob/master/Paystack/UI/PSTCKPaymentCardTextField.m#L396 . All the params are strings.

```
var c: PSTCKCardParams = PSTCKCardParams()
c.number = cardNumber
c.expMonth = expirationMonth
c.expYear = expirationYear
c.cvc = cvc
```

Hope that helps.

**Comment by cosmo1234** [comment]
Conditional statements must have optional type. Your documentation is awesome actually great work

**Comment by ibrahimlawal** [comment]
I get, would rather rewrite it not to have a conditional though. It always will get a value. Was this requirement placed in recent versions? Thanks again for catching the issue and reporting it.

**Comment by cosmo1234** [comment]
Yes recent version.
