### ISSUE TITLE
Access Code does not match public key?

### ISSUE THREAD

**Issue by JittenderKumar** [PaystackHQ/paystack-ios#19]
# Problem/Motivation
(Why the issue was filed, steps to reproduce the problem, etc.)

## Proposed resolution
(Description of the proposed solution, the rationale behind it, and workarounds for people who cannot use the patch.)

## Repeatable
Always|Sometimes|Specific conditions|Specific times

(If it is a bug, you are reporting lease specify:)

## Steps to repeat: (Describe how the issue can be repeated by someone who is to work on it)
1. Step 1
2. Step 2
3. ...

## Expected Results:
(What you expected steps 1, 2 and 3 to give)

## Actual Results:
(What is gave including any error messages, memory dump etc that can help)
Hi
Getting this error "UserInfo={NSLocalizedDescription=There was an error processing your card -- try again in a few seconds, com.paystack.lib:ErrorMessageKey=Access Code does not match public key"
Please help me out?
What is about this error?
Thanks

**Comment by steveamaza** [comment]
Hello, please ensure you are using the proper public key secret key pair.

**Comment by JittenderKumar** [comment]
Yes my public key is correct.
But there is a backendUrlString I didn’t get it. What it is?

**Comment by Whales1992** [comment]
> Yes my public key is correct. But there is a backendUrlString I didn’t get it. What it is? Sent from Jittender’s iPhone
> […](#)

your public key cannot be correct and still get that error! I just help fix same issue for a friend now and it was the same exact error which got fixed after putting the correct key, live key goes with live backEndUrl while test key goes with testBackEndUrl, and simply make sure card is valid by using the provided method card.isValid() if valid, simply call end point backEndUrl+"/new-access-code" and use  access_code like so: final Charge charge = new Charge();
            charge.setCard(card);
            charge.setAccessCode(access_code);
            charge.setAmount(10);
            charge.setEmail("card_owner@mail.com");
That's basically all, you might want to verify transaction before releasing product to client.
