### ISSUE TITLE
Swift 3.0 support

### ISSUE THREAD

**Issue by techmehra** [PaystackHQ/paystack-ios#2]
We are going to integrate this sdk in one of our project, and we are developing that project in swift is there a vision to update this SDK in swift 3.0

**Comment by ibrahimlawal** [comment]
@techmehra I have edited the issue posted. Kindly be clear on what gives you the impression we do not support Swift 3.0

**Comment by ibrahimlawal** [comment]
Hello @techmehra we have updated to use Swift 3 syntax. Thanks for pointing it out. You will also need to update the library to avoid a new issue introduced by Xcode8. You may decide to just add the Keychain access entitlement when building too. The new update only forces you to 🎱
