### ISSUE TITLE
Undefined symbols for architecture arm64:

### ISSUE THREAD

**Issue by Michaelvons** [PaystackHQ/paystack-ios#22]
ignoring file /Users/michaeloshogbunu/WebstormProjects/vendeeReactNative/ios/Paystack.framework/Paystack, file was built for x86_64 which is not the architecture being linked (arm64): /Users/michaeloshogbunu/WebstormProjects/vendeeReactNative/ios/Paystack.framework/Paystack

![screen shot 2019-02-26 at 5 16 49 pm](https://user-images.githubusercontent.com/17091410/53428070-615b1380-39ea-11e9-945b-eea7997c23ea.png)

**Comment by steveamaza** [comment]
Hello @Michaelvons, can you instead use CocoaPods or clone the repo and build?

**Comment by Michaelvons** [comment]
Thanks @steveamaza .
I was able to get everything up and running by installing the SDK afresh via CocoaPods.
