### ISSUE TITLE
usage of Deprecated UIWebView

### ISSUE THREAD

**Issue by demistry** [PaystackHQ/paystack-ios#26]
# Problem/Motivation
Possible rejection of iOS apps due to usage of deprecated UIWebview in PSTCKAuthViewController
![WhatsApp Image 2019-10-15 at 12 07 59](https://user-images.githubusercontent.com/29028996/66826515-80d88980-ef44-11e9-960d-2d77219dfafe.jpeg)

## Proposed resolution
Remove deprecated UIWebView for WKWebView

**Comment by codedentwickler** [comment]
Please, what is the update on this issue? I'm releasing a build to the AppStore in the next couple of days.

**Comment by demistry** [comment]
@codedentwickler my app got approved for the appstore, however it is clearly stated that future submissions with the UIWebview symbol will be rejected. Currently waiting for a pod update, but you can submit your build.

**Comment by codedentwickler** [comment]
Noted. Thank you for the info.
