### ISSUE TITLE
'Fabric+FABKits.h' file not found

### ISSUE THREAD

**Issue by ankitgauravapporio** [PaystackHQ/paystack-ios#37]
# Problem/Motivation
Install new paysatck sdk because of webview issue
## Proposed resolution
'Fabric+FABKits.h' file not found  in PSTCKAPIClient.m
## Repeatable
Always|Sometimes|Specific conditions|Specific times
Always
(If it is a bug, you are reporting lease specify:)

## Steps to repeat: (Describe how the issue can be repeated by someone who is to work on it)
1. Step 1
2. Step 2
3. ...

## Expected Results:
(What you expected steps 1, 2 and 3 to give)

## Actual Results:
(What is gave including any error messages, memory dump etc that can help)

**Comment by ankitgauravapporio** [comment]
![Screenshot 2020-07-24 at 11 58 13 PM](https://user-images.githubusercontent.com/44156688/88423617-a8c91780-ce09-11ea-9ff7-e95f26ab5f30.png)

**Comment by ankitgauravapporio** [comment]
@jubril-paystack why are you not even bother to resolve this issue , i am requesting you please take this matter seriously , many people are waiting for my response, thanks

**Comment by jubril-paystack** [comment]
@ankitgauravapporio My sincere apologies for the late response. Please can share what version of the SDK you have installed? You can check this in your Pod.Lock file if you installed using Cocoapods.

**Comment by ankitgauravapporio** [comment]
hi @jubril-paystack  thank you for the reply , i am using 3.0.14 version , i am pasting screenshot of the paystack version 
![Screenshot 2020-08-07 at 12 54 33 AM](https://user-images.githubusercontent.com/44156688/89573803-ce621200-d848-11ea-94f0-11c1e8f81884.png)

**Comment by JubrilO** [comment]
@ankitgauravapporio The pull request above should fix this issue. To update the SDK run `pod update Paystack`. You may need to run `pod repo update` first to update your local specs repo.

**Comment by jubril-paystack** [comment]
@ankitgauravapporio The pull request above should fix this issue. To update the SDK run `pod update Paystack`. You may need to run `pod repo update` first to update your local specs repo.

**Comment by ankitgauravapporio** [comment]
@jubril-paystack thanks a lot , i really appreciate it.
