### ISSUE TITLE
'new' is unavailable: You cannot directly instantiate an PSTCKTransaction...

### ISSUE THREAD

**Issue by enkkashley** [PaystackHQ/paystack-ios#50]
# Problem
I get this error during build time in Xcode 12.5 in the "PSTCKAPIClient.m" file:
`"'new' is unavailable: You cannot directly instantiate an PSTCKTransaction. You should only use one that has been returned from an PSTCKAPIClient callback."`

## Steps to reproduce
1. Create a new project with Xcode 12.5
2. Install the Paystack SDK(v 3.0.15) using CocoaPods
3. Build the project.

## Expected Results
Successful build.

## Actual Results:
`"'new' is unavailable: You cannot directly instantiate an PSTCKTransaction. You should only use one that has been returned from an PSTCKAPIClient callback."`

![Screenshot 2021-05-01 at 16 42 02](https://user-images.githubusercontent.com/18164589/116788996-307c3a80-aa9c-11eb-93ec-8fc2ca8c10ec.png)

**Comment by KarthiRasuIOS** [comment]
how to install sdk cocoa pods with 3.0.15 I am getting error.

**Comment by KarthiRasuIOS** [comment]
> how to install sdk cocoa pods with 3.0.15 I am getting error.
> Added like this
> pod 'Paystack','~> 3.0.15'

changed pod deployment target but getting same error.

**Comment by ravi-paystack** [comment]
@enkkashley thanks for pointing this out. We are looking into this.

**Comment by ravi-paystack** [comment]
@KarthiRasuIOS thank you. Can you post this as a separate issue with details on the error you are getting?

**Comment by enkkashley** [comment]
> @enkkashley thanks for pointing this out. We are looking into this.

you're welcome. alright.
