### ISSUE TITLE
_OBJC_CLASS_$_PSTCKTransactionParams

### ISSUE THREAD

**Issue by jaipreetSingh50** [PaystackHQ/paystack-ios#6]
file was built for x86_64 which is not the architecture being linked (arm64)

i'm working in Xcode 8.1 in objective C. The library is working fine in the stimulater. When i try to run it on my device iPhone 6 (10.1) 

Xcode shows the error 
ld: warning: ignoring file /Users/osx/Desktop/SAMagazine/Paystack.framework/Paystack, file was built for x86_64 which is not the architecture being linked (arm64): /Users/osx/Desktop/SAMagazine/Paystack.framework/Paystack
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_PSTCKTransactionParams", referenced from:
      objc-class-ref in SubscriptionViewController.o
![screen shot 2016-12-07 at 9 41 38 am](https://cloud.githubusercontent.com/assets/24425380/20954446/641a4482-bc61-11e6-813f-9e48ced05ab6.png)

**Comment by uchechukwudim** [comment]
using Xcode 8.1.. getting error "PSTCKTransactionParams.h not found
![screen shot 2016-12-08 at 1 40 32 am](https://cloud.githubusercontent.com/assets/12687196/20992876/46536290-bce7-11e6-9065-552912670046.png)
![screen shot 2016-12-08 at 1 39 42 am](https://cloud.githubusercontent.com/assets/12687196/20992891/5a83172e-bce7-11e6-9f59-732828dd3206.png)

"

**Comment by ibrahimlawal** [comment]
Hello @jaipreetSingh50 @uchechukwudim I just uploaded a release that should fix this. Kindly update to v2.2.0

**Comment by jaipreetSingh50** [comment]
Hello @ibrahimlawal , thanks you update 
But Paystack.framework is missing in new release.

**Comment by ibrahimlawal** [comment]
Errr, I don't get. There's an attachment on the release page. Does that not work?

**Comment by uchechukwudim** [comment]
thanks for your response Lawal. what i downloaded was v2.2.0 still same error "PSTCKTransactionParams.h not found.

**Comment by jaipreetSingh50** [comment]
hello 
i did not get the updated framework file in updated release.
If that is not needed. Please tell me how can i fix the error in my project

**Comment by ibrahimlawal** [comment]
@jaipreetSingh50 Here is a direct link to the most recent build. Remember to delete any one you added to your project previously:

https://github.com/PaystackHQ/paystack-ios/releases/download/v2.2.0/PaystackiOS.zip

**Comment by Michaelvons** [comment]
Hello please i just got this error

**Comment by Michaelvons** [comment]
ignoring file /Users/michaeloshogbunu/WebstormProjects/vendeeReactNative/ios/Paystack.framework/Paystack, file was built for x86_64 which is not the architecture being linked (arm64): /Users/michaeloshogbunu/WebstormProjects/vendeeReactNative/ios/Paystack.framework/Paystack

**Comment by SaadIEng** [comment]
@jaipreetSingh50 @ibrahimlawal have the issue been fixed??? 
**Paystack, file was built for x86_64 which is not the architecture being linked (arm64)**
