### ISSUE TITLE
chargeCard Method of the paystack iOS SDK does not trigger didRequestValidation: handler when a card user is requested to input his PIN.

### ISSUE THREAD

**Issue by Ehiss** [PaystackHQ/paystack-ios#8]
# Problem/Motivation
When card Payment is to be made by Secured ATM card holders in particular, they are requested to enter their PIN. The SDK recognizes this and attempts to display a popup for the user to enter his PIN. However the method does not call the "didRequestValidation:" handler to enable users of the SDK know this has occurred.

## Proposed resolution
The chardeCard method should trigger the didRequestValidation: handler to notify users of the SDK of this scenario. 

## Repeatable
It happens anytime a Secured ATM card holder is trying to make payment with his/her card

(If it is a bug, you are reporting lease specify:)

## Steps to repeat: (Describe how the issue can be repeated by someone who is to work on it)
1. Step 1
2. Step 2
3. ...

## Expected Results:
(What you expected steps 1, 2 and 3 to give)

## Actual Results:
(What is gave including any error messages, memory dump etc that can help)

**Comment by ibrahimlawal** [comment]
@Ehiss we have updated the framework to give notify you when our dialogs are about to be shown and when they are dismissed. By providing `willShowDialog` and `dialogDismissed` completions, you can ensure the dialogs are not covered.
